"""Build Kayla's Kitchen from src/.

Writes:
  index.html            standalone page for GitHub Pages (full HTML document)
  dist/artifact.html    page body for the Claude artifact (host adds the skeleton)

Usage: python3 build.py
"""
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"
DATA_FILES = ["data1.js", "data2.js", "data3.js", "data4.js", "data5.js"]

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="Kayla's Kitchen: 50 Southern comfort classics with step-by-step cook mode, herbs and spices guide, cooking methods, lessons and a cooking journal.">
<meta name="theme-color" content="#2D5B44">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="32x32" href="icons/icon-32.png">
<link rel="apple-touch-icon" href="icons/icon-180.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Kayla's Kitchen">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
"""
# Registers the offline worker on the public site only (the Claude artifact has no worker).
SW_REGISTER = """<script>
if ("serviceWorker" in navigator) { window.addEventListener("load", function () { navigator.serviceWorker.register("sw.js").catch(function () {}); }); }
</script>
"""
# Offline support: the app shell is cached so the app opens without signal; when online it always fetches the newest version first.
SW_TEMPLATE = """// Generated by build.py. The cache name changes on every build so phones pick up updates.
const CACHE = "kk-__VERSION__";
const SHELL = ["./", "./index.html", "./manifest.webmanifest", "./icons/icon-192.png", "./icons/icon-512.png", "./icons/icon-180.png"];
self.addEventListener("install", e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener("activate", e => { e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", e => {
  const req = e.request; if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin === location.origin) {
    // network first, so a fresh deploy shows up right away; fall back to the cached copy offline
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res; })
      .catch(() => caches.match(req).then(r => r || caches.match("./index.html"))));
  } else if (url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com") {
    e.respondWith(caches.match(req).then(r => r || fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return res; })));
  }
  // everything else (YouTube videos and thumbnails) goes straight to the network
});
"""
RESET = "<style>:root{padding-top:env(safe-area-inset-top,0px)}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n"


def main():
    app = (SRC / "app.html").read_text(encoding="utf-8")
    data = "".join((SRC / f).read_text(encoding="utf-8") for f in DATA_FILES)
    if "/*DATA*/" not in app:
        raise SystemExit("app.html is missing the /*DATA*/ marker")
    body = app.replace("/*DATA*/", data)

    (ROOT / "dist").mkdir(exist_ok=True)
    (ROOT / "dist" / "artifact.html").write_text(body, encoding="utf-8")

    cut = body.index("</style>") + len("</style>")
    page = HEAD + body[:cut] + "\n" + RESET + "</head>\n<body>\n" + body[cut:] + "\n" + SW_REGISTER + "</body>\n</html>\n"
    (ROOT / "index.html").write_text(page, encoding="utf-8")
    import hashlib
    version = hashlib.sha1(page.encode("utf-8")).hexdigest()[:10]
    (ROOT / "sw.js").write_text(SW_TEMPLATE.replace("__VERSION__", version), encoding="utf-8")
    print("built index.html and dist/artifact.html")


if __name__ == "__main__":
    main()
