
{id:"peach-cobbler",n:"Peach Cobbler",c:"Desserts",p:"sweet",d:1,t:70,s:8,k:[],sp:["cinnamon","nutmeg"],
tip:"Don't stir after you pour. The batter rises up around the peaches on its own.",
i:[[6,"cup","sliced peaches (fresh or frozen)"],[1,"cup","sugar (for the fruit)"],[1,"tsp","cinnamon"],[0.25,"tsp","nutmeg"],[1,"tbsp","lemon juice"],[0.5,"cup","butter"],[1,"cup","all-purpose flour"],[1,"cup","sugar (for the batter)"],[2,"tsp","baking powder"],[0.25,"tsp","salt"],[1,"cup","milk"]],
st:[["Heat the oven to 350°F.",0],["Simmer the peaches with sugar, cinnamon, nutmeg and lemon juice until juicy.",5],["Melt the butter in a 9×13 dish in the oven.",5],["Whisk the flour, sugar, baking powder, salt and milk. Pour it over the butter without stirring.",0],["Spoon the peaches and juice over the batter. Don't stir.",0],["Bake until golden.",42],["Cool a little before serving, ideally with vanilla ice cream.",15]]},

{id:"banana-pudding",n:"Banana Pudding",c:"Desserts",p:"sweet",d:2,t:45,s:10,w:"Chill 4 hrs",k:["custard"],sp:["vanilla"],
tip:"Layer the pudding while it's warm. It softens the wafers into a cake-like texture.",
i:[[0.75,"cup","sugar"],[0.33,"cup","all-purpose flour"],[0.25,"tsp","salt"],[3,"cup","whole milk"],[4,"","egg yolks"],[2,"tbsp","butter"],[2,"tsp","vanilla"],[1,"box","(11 oz) vanilla wafers"],[5,"","ripe bananas, sliced"],[2,"cup","whipped cream"]],
st:[["Whisk the sugar, flour and salt in a saucepan, then whisk in the milk and egg yolks.",0],["Cook over medium heat, stirring constantly, until thick like pudding.",11],["Off the heat, stir in the butter and vanilla.",0],["Layer wafers, bananas and warm pudding in a dish. Repeat 2–3 times.",0],["Cover the surface with plastic and chill.",240],["Top with whipped cream before serving.",0]]},

{id:"pecan-pie",n:"Pecan Pie",c:"Desserts",p:"sweet",d:2,t:75,s:8,w:"Cool 2 hrs",k:["custard"],sp:["vanilla"],
tip:"If the crust edge browns too fast, cover it with a ring of foil.",
i:[[1,"","unbaked 9-inch pie crust"],[1,"cup","light corn syrup"],[1,"cup","brown sugar"],[3,"","eggs"],[0.33,"cup","butter, melted"],[1,"tsp","vanilla"],[0.25,"tsp","salt"],[1.5,"cup","pecan halves"]],
st:[["Heat the oven to 350°F and fit the crust into a pie plate.",0],["Whisk the corn syrup, brown sugar, eggs, butter, vanilla and salt.",0],["Scatter the pecans in the crust and pour the filling over.",0],["Bake until the edges are set and the center has a slight jiggle.",58],["Cool completely so the filling sets.",120]]},

{id:"sweet-potato-pie",n:"Sweet Potato Pie",c:"Desserts",p:"sweet",d:2,t:120,s:8,w:"Cool 2 hrs",k:["custard"],sp:["cinnamon","nutmeg","vanilla"],
tip:"Bake the sweet potatoes instead of boiling them. The flavor is deeper and the filling isn't watery.",
i:[[2,"cup","mashed baked sweet potatoes"],[0.5,"cup","butter, softened"],[1,"cup","sugar"],[2,"","eggs"],[0.5,"cup","evaporated milk"],[1,"tsp","vanilla"],[0.5,"tsp","cinnamon"],[0.5,"tsp","nutmeg"],[0.25,"tsp","salt"],[1,"","unbaked 9-inch pie crust"]],
st:[["Bake the sweet potatoes at 400°F until very soft. Peel and mash them.",55],["Lower the oven to 350°F. Beat the potatoes, butter and sugar smooth, then beat in the eggs, milk, vanilla, spices and salt.",0],["Pour into the crust.",0],["Bake until the center is nearly set.",52],["Cool completely before slicing.",120]]},

{id:"red-velvet",n:"Red Velvet Cake",c:"Desserts",p:"sweet",d:3,t:120,s:12,k:["cream"],sp:["vanilla"],
tip:"Room-temperature buttermilk and eggs blend smoothly and give the cake a fine, tender crumb.",
i:[[2.5,"cup","all-purpose flour"],[1.5,"cup","sugar"],[1,"tsp","baking soda"],[1,"tsp","salt"],[1,"tbsp","cocoa powder"],[1.5,"cup","vegetable oil"],[1,"cup","buttermilk, room temperature"],[2,"","eggs, room temperature"],[2,"tbsp","red food coloring"],[1,"tsp","white vinegar"],[1,"tsp","vanilla"],[16,"oz","cream cheese, softened (frosting)"],[0.5,"cup","butter, softened (frosting)"],[4,"cup","powdered sugar"],[2,"tsp","vanilla (frosting)"]],
st:[["Heat the oven to 350°F. Grease and flour two 9-inch pans.",0],["Whisk the flour, sugar, baking soda, salt and cocoa.",0],["Whisk the oil, buttermilk, eggs, food coloring, vinegar and vanilla, then stir into the dry mix until smooth.",0],["Divide between the pans and bake until a toothpick comes out clean.",28],["Cool 10 minutes in the pans, then turn out and cool completely.",70],["Beat the cream cheese and butter, then beat in the powdered sugar and vanilla. Frost between the layers and all over.",0]]},

{id:"pound-cake",n:"Classic Pound Cake",c:"Desserts",p:"sweet",d:2,t:120,s:12,k:["cream"],sp:["vanilla"],
tip:"Creaming the butter and sugar long enough is what makes the cake rise. Set a timer.",
i:[[1,"cup","butter, softened"],[0.5,"cup","shortening"],[3,"cup","sugar"],[5,"","eggs, room temperature"],[3,"cup","all-purpose flour"],[0.5,"tsp","baking powder"],[0.25,"tsp","salt"],[1,"cup","whole milk"],[2,"tsp","vanilla"]],
st:[["Heat the oven to 325°F. Grease and flour a tube or Bundt pan.",0],["Beat the butter, shortening and sugar until pale and fluffy.",6],["Beat in the eggs one at a time.",0],["Whisk the flour, baking powder and salt. Add to the batter alternating with the milk, starting and ending with flour. Stir in the vanilla.",0],["Pour into the pan and bake until a skewer comes out clean.",80],["Cool in the pan, then turn out.",15]]},

{id:"hummingbird-cake",n:"Hummingbird Cake",c:"Desserts",p:"sweet",d:2,t:100,s:12,k:["cream"],sp:["cinnamon","vanilla"],
tip:"Stir by hand. A mixer overworks this batter and makes it tough.",
i:[[3,"cup","all-purpose flour"],[2,"cup","sugar"],[1,"tsp","baking soda"],[1,"tsp","salt"],[1,"tsp","cinnamon"],[3,"","eggs, beaten"],[1,"cup","vegetable oil"],[1.5,"tsp","vanilla"],[1,"can","(8 oz) crushed pineapple, undrained"],[2,"cup","mashed ripe bananas"],[1,"cup","chopped pecans"],[16,"oz","cream cheese, softened (frosting)"],[0.5,"cup","butter, softened (frosting)"],[4,"cup","powdered sugar"]],
st:[["Heat the oven to 350°F and grease three 9-inch pans.",0],["Whisk the flour, sugar, baking soda, salt and cinnamon.",0],["Stir in the eggs and oil just until moistened. Fold in the vanilla, pineapple, bananas and pecans.",0],["Divide among the pans and bake until a toothpick comes out clean.",25],["Cool 10 minutes, turn out and cool completely.",60],["Beat the cream cheese, butter and powdered sugar. Stack and frost.",0]]},

{id:"sweet-tea",n:"Southern Sweet Tea",c:"Drinks",p:"sweet",d:1,t:20,s:8,w:"Chill 1 hr",k:[],sp:[],
tip:"A tiny pinch of baking soda smooths out bitterness and keeps the tea clear.",
i:[[4,"cup","water (to boil)"],[3,"","family-size tea bags (or 8 regular)"],[0.125,"tsp","baking soda"],[1,"cup","sugar"],[4,"cup","cold water"],[1,"","lemon, sliced"]],
st:[["Bring 4 cups of water to a boil, then take it off the heat.",5],["Add the tea bags and baking soda and steep. Don't squeeze the bags.",10],["Remove the bags and stir in the sugar until it dissolves.",0],["Add the cold water, chill, and serve over ice with lemon.",60]]}
];

const TECHNIQUES = [
{id:"roux",n:"Making a Roux",eli:"A roux is flour cooked in fat. Raw flour tastes like paste, so you cook it first. The longer you stir, the darker and nuttier it gets, but the less it thickens.",pts:["Use about equal parts fat and flour.","A blond roux (2–15 minutes) thickens gravy and mac and cheese. A dark roux (30–45 minutes) flavors gumbo.","Stir the whole time. Black specks mean it burned, so start over."],q:"Which roux thickens the most?",o:["A light blond roux","A dark chocolate-brown roux","They thicken the same"],a:0},
{id:"trinity",n:"The Holy Trinity",eli:"Onion, celery and green bell pepper, chopped and cooked together. It's the flavor base of Cajun and Creole food, like the French use onion, celery and carrot.",pts:["Dice everything about the same size so it cooks evenly.","A rough ratio is 2 parts onion to 1 part celery to 1 part pepper.","Adding it to a hot roux stops the roux from browning further."],q:"In the trinity, green bell pepper takes the place of which French vegetable?",o:["Garlic","Carrot","Okra"],a:1},
{id:"dredge",n:"Dredging",eli:"Dredging means coating food in something dry, then wet, then dry again, so a crunchy crust sticks to it when you fry.",pts:["Use one hand for dry and one for wet so your fingers don't get clumpy.","Press the coating on firmly.","Let coated pieces rest 10–15 minutes so the coating sets and won't fall off in the oil."],q:"Why rest coated chicken before frying?",o:["Only to warm it up","So the coating sets and sticks","To dry out the meat"],a:1},
{id:"fry",n:"Frying Temperature",eli:"Oil for frying sits between 325°F and 375°F. Too cold and food soaks up oil and turns greasy. Too hot and the outside burns before the inside cooks.",pts:["Use a clip-on thermometer. No thermometer? A bread cube browns in about 60 seconds at 350°F.","Fry in small batches so the temperature doesn't crash.","Drain on a wire rack and salt right away. Never put water on a grease fire; cover it with a lid."],q:"Your fried chicken came out greasy. What's the most likely cause?",o:["The oil was too cold","The oil was too hot","Too much salt"],a:0},
{id:"biscuit",n:"The Biscuit Method",eli:"Bits of cold butter are mixed into flour. In the hot oven, the butter melts and turns to steam, which puffs up flaky layers.",pts:["Keep the butter and buttermilk cold. Freeze the butter 15 minutes if your kitchen is warm.","Mix only until it holds together. Overworked dough makes tough biscuits.","Cut straight down. Twisting the cutter seals the edges and stops the rise."],q:"Why do biscuits need cold butter?",o:["It turns to steam in the oven and makes layers","It makes the dough sweeter","Warm butter is unsafe"],a:0},
{id:"braise",n:"Braising and Smothering",eli:"Brown the meat, then cook it slowly, covered, in a little liquid until tough meat turns tender. Smothering is the Southern version, usually in onion gravy.",pts:["Brown the meat well. Those browned bits flavor the sauce.","The liquid comes partway up the meat, not over it.","Keep it at a bare simmer, not a boil, so the meat stays juicy."],q:"What should the liquid be doing while you braise?",o:["Rolling boil","Gentle, barely bubbling simmer","Nothing; the heat is off"],a:1},
{id:"lowslow",n:"Low and Slow Barbecue",eli:"Tough cuts like pork shoulder are full of connective tissue. Hours at low heat melt it into gelatin, which makes the meat tender and juicy.",pts:["Cook to internal temperature and feel, not to time.","The temperature often stalls around 160°F for hours. Wrapping the meat in foil or paper pushes it through.","Rest the meat 30 minutes or more before pulling it."],q:"Pulled pork is ready to shred at about:",o:["145°F","165°F","200°F"],a:2},
{id:"custard",n:"Custards and Puddings",eli:"Eggs set when they heat up. Gentle heat makes them smooth and creamy. Too much heat scrambles them.",pts:["On the stove, stir constantly and scrape the bottom corners.","Temper eggs by whisking in a little hot liquid before adding them to the pot.","Pies are done when the edges are set and the center still jiggles a little. They firm up as they cool."],q:"A pecan pie is done when:",o:["The center is completely firm","The edges are set and the center jiggles slightly","The crust turns dark brown"],a:1},
{id:"cream",n:"Creaming Butter and Sugar",eli:"Beating soft butter with sugar traps tiny air bubbles. Those bubbles are what make a pound cake rise light instead of heavy.",pts:["Butter should be soft but cool, about 65°F. It dents when you press it.","Beat 5–7 minutes, until pale and fluffy.","Add eggs one at a time, and add dry and wet ingredients in turns so the batter doesn't split."],q:"How long should you cream butter and sugar for pound cake?",o:["30 seconds","5–7 minutes","Overnight"],a:1},
{id:"castiron",n:"Cast-Iron Care",eli:"Seasoning is layers of oil baked onto the iron. It makes the skillet naturally nonstick and gets better the more you cook in it.",pts:["Preheat the skillet. Hot iron gives cornbread its crunchy crust.","Wash with hot water and a brush (a little soap is fine). Dry it on the burner and wipe on a thin coat of oil.","Avoid long simmers of acidic food like tomato sauce in a newer pan."],q:"After washing a cast-iron skillet, you should:",o:["Let it air-dry in the rack","Dry it on the heat and rub in a thin coat of oil","Soak it overnight"],a:1},
{id:"gravy",n:"Pan Gravy",eli:"Gravy starts as a roux made from the drippings left in the pan. Add milk for cream gravy, or stock for brown gravy.",pts:["Keep the browned bits in the pan. They're the flavor.","Pour the liquid in slowly while whisking to avoid lumps.","Gravy thickens as it cools, so stop when it's a little thinner than you want. Use plenty of black pepper."],q:"How do you avoid lumpy gravy?",o:["Dump all the milk in at once","Add the liquid slowly while whisking","Skip the flour"],a:1},
{id:"potliquor",n:"Pot Liquor",eli:"Pot liquor is the rich, smoky broth left after simmering greens or beans with smoked meat. It's full of flavor and nutrients.",pts:["Simmer the smoked meat first to build the broth before the greens go in.","Wash greens until there's no grit left in the sink.","A splash of vinegar and a pinch of sugar balance the bitterness."],q:"What's pot liquor traditionally eaten with?",o:["Cornbread","Ice cream","Pound cake"],a:0},
{id:"grits",n:"Cooking Grits",eli:"Grits are ground dried corn. Stone-ground grits are coarse and need 30–45 minutes of slow simmering. Instant grits are fast but have less flavor.",pts:["Use about 4 parts liquid to 1 part grits.","Whisk the grits in slowly to prevent lumps.","Stir often and add hot water if they get stiff. Finish with butter and salt."],q:"What's the usual liquid-to-grits ratio?",o:["1 to 1","4 to 1","10 to 1"],a:1}
];

const PROTEINS = [
{id:"chicken",n:"Chicken"},{id:"pork",n:"Pork"},{id:"beef",n:"Beef"},{id:"seafood",n:"Seafood"},{id:"veg",n:"Vegetables & Beans"},{id:"eggs",n:"Eggs, Dairy & Breads"},{id:"sweet",n:"Sweets & Drinks"}
];

const SPICES = [
{id:"black-pepper",n:"Black Pepper",t:"Spice",f:"Warm, sharp heat. The backbone of Southern seasoning.",use:"Season everything savory. Cream gravy should be speckled with it.",best:["chicken","beef","pork","eggs","veg"]},
{id:"cayenne",n:"Cayenne",t:"Spice",f:"Clean, fiery heat with little flavor of its own.",use:"Start with a pinch. It's the fire in Nashville hot chicken and a kick in flour dredges.",best:["chicken","seafood","eggs"]},
{id:"paprika",n:"Paprika",t:"Spice",f:"Sweet, mild pepper flavor and a warm red color.",use:"Gives fried chicken its golden-red crust and tops deviled eggs and potato salad.",best:["chicken","pork","eggs"]},
{id:"smoked-paprika",n:"Smoked Paprika",t:"Spice",f:"Sweet pepper with a campfire smokiness.",use:"Adds smoky depth to mac and cheese and spice pastes without a smoker.",best:["chicken","pork","eggs"]},
{id:"garlic-powder",n:"Garlic Powder",t:"Spice",f:"Mellow, toasty garlic that blends evenly into dry mixes.",use:"Use in dredges and rubs, where fresh garlic would burn.",best:["chicken","beef","pork","veg"]},
{id:"onion-powder",n:"Onion Powder",t:"Spice",f:"Sweet, savory onion flavor in dry form.",use:"Rounds out flour dredges and meatloaf.",best:["chicken","beef"]},
{id:"cajun",n:"Cajun Seasoning",t:"Blend",f:"Paprika, cayenne, garlic, onion, black pepper and herbs in one jar.",use:"The quick route to Louisiana flavor in gumbo, jambalaya, étouffée and fried fish.",best:["seafood","chicken","pork"]},
{id:"old-bay",n:"Old Bay",t:"Blend",f:"Celery salt, paprika, mustard and warm spices. Briny and savory.",use:"Made for seafood: boils, croquettes, crab and shrimp.",best:["seafood"]},
{id:"poultry",n:"Poultry Seasoning",t:"Blend",f:"Sage, thyme, marjoram and rosemary. Smells like Thanksgiving.",use:"Seasons smothered chicken and cornbread dressing.",best:["chicken","veg"]},
{id:"thyme",n:"Thyme",t:"Herb",f:"Earthy, lightly minty and savory.",use:"Holds up to long cooking, so it goes into braises, gumbo, red beans and pot pie.",best:["beef","chicken","pork"]},
{id:"bay",n:"Bay Leaf",t:"Herb",f:"Subtle, tea-like and herbal. You notice it most when it's missing.",use:"Drop 1–2 leaves into beans, stocks and gumbo. Take them out before serving.",best:["pork","chicken","seafood","veg"]},
{id:"sage",n:"Sage",t:"Herb",f:"Piney, savory and slightly peppery.",use:"The signature flavor of cornbread dressing and breakfast sausage gravy.",best:["pork","chicken","veg"]},
{id:"file",n:"Filé Powder",t:"Herb",f:"Ground sassafras leaves. Earthy, like root beer and eucalyptus.",use:"Stir into gumbo at the table, off the heat. It thickens and flavors.",best:["seafood","chicken"]},
{id:"garlic",n:"Fresh Garlic",t:"Herb",f:"Pungent and sharp raw, sweet and nutty when cooked.",use:"Add after the onions soften so it doesn't burn. Goes in almost every savory pot.",best:["chicken","beef","pork","seafood","veg"]},
{id:"green-onion",n:"Green Onions",t:"Herb",f:"Fresh, mild onion bite.",use:"Sprinkle on gumbo, jambalaya and shrimp and grits right before serving.",best:["seafood","chicken","pork"]},
{id:"red-pepper-flakes",n:"Red Pepper Flakes",t:"Spice",f:"Dried chile with slow-building heat.",use:"Wakes up greens, cabbage, black-eyed peas and vinegar barbecue sauce.",best:["veg","pork"]},
{id:"celery-seed",n:"Celery Seed",t:"Spice",f:"Concentrated, slightly bitter celery flavor.",use:"The classic secret in coleslaw and potato salad.",best:["veg","eggs"]},
{id:"allspice",n:"Allspice",t:"Spice",f:"Tastes like cinnamon, clove and nutmeg in one berry.",use:"Warms up braised oxtails and rich meat gravies.",best:["beef","pork"]},
{id:"cinnamon",n:"Cinnamon",t:"Spice",f:"Sweet, woody warmth.",use:"Candied yams, peach cobbler, sweet potato pie and hummingbird cake.",best:["sweet","veg"]},
{id:"nutmeg",n:"Nutmeg",t:"Spice",f:"Warm, sweet and slightly nutty. A little goes a long way.",use:"Grate into sweet potato pie, cobbler and corn pudding.",best:["sweet","veg","eggs"]},
{id:"vanilla",n:"Vanilla",t:"Spice",f:"Sweet, floral and round.",use:"The base note in banana pudding, pound cake and nearly every Southern dessert.",best:["sweet"]}
];

const PATH = [
{n:"First Steps",d:"No-fail basics that teach measuring, boiling and seasoning.",r:["sweet-tea","deviled-eggs","pimento-cheese","cheese-grits","coleslaw","skillet-cornbread"]},
{n:"Sunday Sides",d:"The supper-table classics. You'll learn greens, baking and a simple custard.",r:["collard-greens","mac-cheese","candied-yams","biscuits","banana-pudding","peach-cobbler"]},
{n:"The Main Event",d:"Braising, smothering and your first frying.",r:["smothered-chicken","meatloaf","red-beans-rice","pot-roast","fried-catfish","shrimp-grits"]},
{n:"Pitmaster and Fry Cook",d:"The big projects: dark roux, deep frying and low-and-slow barbecue.",r:["fried-chicken","chicken-fried-steak","gumbo","pulled-pork","etouffee","red-velvet"]}
];
