const RECIPES = [
{id:"fried-chicken",n:"Southern Fried Chicken",c:"Mains",p:"chicken",d:3,t:75,s:4,w:"Brine 4 hrs or overnight",k:["dredge","fry","castiron"],sp:["black-pepper","cayenne","paprika","garlic-powder","onion-powder"],
tip:"Let the oil climb back to temperature between batches. A crowded pan drops the heat and gives you greasy chicken.",
i:[[1,"","whole chicken (3–4 lb), cut into 8 pieces"],[2,"cup","buttermilk"],[2,"tbsp","hot sauce"],[1,"tbsp","kosher salt, divided"],[2,"cup","all-purpose flour"],[1,"tbsp","paprika"],[2,"tsp","garlic powder"],[1,"tsp","onion powder"],[1,"tsp","black pepper"],[0.5,"tsp","cayenne"],[6,"cup","peanut or vegetable oil, for frying"]],
st:[["Stir the buttermilk, hot sauce and half the salt together. Submerge the chicken, cover and chill at least 4 hours or overnight.",0],["Whisk the flour, paprika, garlic powder, onion powder, black pepper, cayenne and the rest of the salt in a wide dish.",0],["Lift each piece from the buttermilk, let the extra drip off, and press it firmly into the flour on all sides. Rest the pieces on a rack so the coating sets.",15],["Heat the oil in a deep cast-iron skillet or Dutch oven to 325–350°F.",10],["Fry the dark meat first, a few pieces at a time, turning every few minutes, until deep golden and 175°F inside.",13],["Fry the white meat until it reads 165°F inside. Drain on a wire rack, not paper towels, so the bottom stays crisp.",11]]},

{id:"chicken-dumplings",n:"Chicken and Dumplings",c:"Mains",p:"chicken",d:2,t:90,s:6,k:["biscuit"],sp:["bay","black-pepper","thyme"],
tip:"Drop the dumplings into broth at a rolling boil so they firm up fast, then lower to a simmer so they don't fall apart.",
i:[[3,"lb","bone-in chicken thighs and breasts"],[10,"cup","water"],[1,"","onion, quartered"],[2,"","celery ribs, chopped"],[2,"","carrots, sliced"],[2,"","bay leaves"],[2,"tsp","kosher salt"],[1,"tsp","black pepper"],[2,"cup","all-purpose flour (dumplings)"],[1,"tsp","baking powder"],[0.5,"tsp","salt (dumplings)"],[4,"tbsp","cold butter"],[0.75,"cup","buttermilk"]],
st:[["Put the chicken, water, onion, celery, carrots, bay leaves, salt and pepper in a big pot. Cover and simmer.",45],["Lift out the chicken and let it cool. Shred the meat and throw away the skin and bones. Fish out the onion and bay leaves.",0],["For the dumplings, whisk the flour, baking powder and salt. Rub in the cold butter with your fingers, then stir in the buttermilk to make a stiff dough.",0],["Roll the dough on a floured counter about ⅛ inch thick and cut it into 1×2-inch strips.",0],["Bring the broth to a rolling boil. Drop the strips in one at a time, stirring gently.",0],["Lower to a simmer, add the chicken back, and cook until the dumplings are cooked through and the broth thickens.",18]]},

{id:"shrimp-grits",n:"Shrimp and Grits",c:"Mains",p:"seafood",d:2,t:50,s:4,k:["grits","castiron"],sp:["cajun","garlic","green-onion"],
tip:"Pull the shrimp the moment they curl into a C. An O shape means overcooked.",
i:[[1,"cup","stone-ground grits"],[4,"cup","water or chicken stock"],[1,"tsp","salt"],[1,"cup","sharp cheddar, shredded"],[2,"tbsp","butter"],[4,"slice","bacon, chopped"],[1,"lb","large shrimp, peeled and deveined"],[1,"tsp","Cajun seasoning"],[3,"","garlic cloves, minced"],[0.5,"cup","chicken stock (sauce)"],[1,"tbsp","lemon juice"],[3,"","green onions, sliced"]],
st:[["Bring the water and salt to a boil. Whisk in the grits slowly, then simmer on low, stirring often, until thick and creamy.",35],["Stir in the butter and cheese. Cover and keep warm.",0],["Cook the bacon in a skillet until crisp. Lift it out and leave the fat in the pan.",6],["Toss the shrimp with Cajun seasoning. Sear in the bacon fat 1–2 minutes per side until pink, then add the garlic for 30 seconds.",3],["Pour in the stock and lemon juice, scrape up the browned bits, simmer 1 minute and stir the bacon back in.",1],["Spoon the shrimp and pan sauce over the grits and top with green onions.",0]]},

{id:"chicken-fried-steak",n:"Chicken-Fried Steak",c:"Mains",p:"beef",d:2,t:40,s:4,k:["dredge","fry","gravy"],sp:["black-pepper","garlic-powder","paprika"],
tip:"Be generous with black pepper in the cream gravy. It should look speckled.",
i:[[4,"","cube steaks (about 4 oz each)"],[1.5,"cup","all-purpose flour"],[1,"tsp","salt"],[1,"tsp","black pepper"],[1,"tsp","garlic powder"],[0.5,"tsp","paprika"],[2,"","eggs"],[1,"cup","milk"],[1,"cup","vegetable oil"],[3,"tbsp","flour (gravy)"],[2,"cup","whole milk (gravy)"]],
st:[["Season the flour with salt, pepper, garlic powder and paprika. Whisk the eggs with 1 cup milk in another dish.",0],["Dredge each steak in flour, then egg, then flour again, pressing hard. Let them rest.",10],["Heat ½ inch of oil in a cast-iron skillet to 350°F. Fry the steaks 3–4 minutes per side until golden. Drain on a rack.",8],["Pour off all but 3 tablespoons of oil, keeping the browned bits. Whisk in the 3 tablespoons flour and cook 1–2 minutes.",2],["Slowly whisk in 2 cups milk. Simmer until thick, then season with plenty of pepper.",4],["Serve the steaks smothered in gravy.",0]]},

{id:"smothered-pork-chops",n:"Smothered Pork Chops",c:"Mains",p:"pork",d:2,t:60,s:4,k:["dredge","roux","braise"],sp:["black-pepper","garlic-powder","garlic","thyme"],
tip:"Don't wash out the skillet after browning. Those stuck-on bits are the flavor of the gravy.",
i:[[4,"","bone-in pork chops, ¾ inch thick"],[1,"tsp","salt"],[1,"tsp","black pepper"],[1,"tsp","garlic powder"],[0.5,"cup","all-purpose flour"],[3,"tbsp","vegetable oil"],[1,"","large onion, sliced"],[2,"","garlic cloves, minced"],[2,"cup","chicken stock"],[0.5,"cup","heavy cream"]],
st:[["Season the chops and dredge them in flour. Save 2 tablespoons of the flour.",0],["Brown the chops in the oil 3–4 minutes per side, then set them aside.",8],["Cook the onion until soft, then add the garlic.",6],["Sprinkle in the saved flour and stir to make a light roux.",2],["Whisk in the stock, scraping the pan. Nestle the chops back in, cover and simmer on low until tender.",30],["Stir in the cream, simmer 2 minutes and spoon the gravy over the chops.",2]]},

{id:"meatloaf",n:"Southern Meatloaf",c:"Mains",p:"beef",d:1,t:75,s:6,k:[],sp:["black-pepper","onion-powder"],
tip:"Mix with your hands only until combined. Overmixing makes a dense, tough loaf.",
i:[[2,"lb","ground beef (80/20)"],[1,"","onion, finely chopped"],[2,"","eggs"],[0.75,"cup","crushed saltine crackers"],[0.5,"cup","milk"],[2,"tbsp","Worcestershire sauce"],[1.5,"tsp","salt"],[1,"tsp","black pepper"],[0.75,"cup","ketchup (glaze)"],[3,"tbsp","brown sugar"],[1,"tbsp","apple cider vinegar"]],
st:[["Heat the oven to 350°F and line a sheet pan.",0],["Soak the crackers in the milk.",5],["Add the beef, onion, eggs, Worcestershire, salt and pepper. Mix with your hands just until combined, and shape a loaf about 9×5 inches on the pan.",0],["Stir the ketchup, brown sugar and vinegar together. Brush half over the loaf.",0],["Bake 45 minutes, brush on the rest of the glaze, and bake 15 minutes more until 160°F inside.",60],["Rest before slicing.",10]]},

{id:"pulled-pork",n:"Carolina Pulled Pork",c:"Mains",p:"pork",d:2,t:480,s:10,w:"Rub rests 1 hr+",k:["lowslow"],sp:["paprika","cayenne","black-pepper","garlic-powder","red-pepper-flakes"],
tip:"Cook to temperature and feel, not the clock. It's ready when a fork twists in with no resistance.",
i:[[6,"lb","bone-in pork shoulder (Boston butt)"],[2,"tbsp","brown sugar"],[2,"tbsp","paprika"],[1,"tbsp","kosher salt"],[1,"tbsp","black pepper"],[2,"tsp","garlic powder"],[1,"tsp","cayenne"],[1,"cup","apple cider vinegar"],[0.5,"cup","water"],[1,"tbsp","red pepper flakes"],[1,"tbsp","sugar"]],
st:[["Mix the brown sugar, paprika, salt, pepper, garlic powder and cayenne. Rub it all over the pork and let it sit.",60],["Set a smoker or oven to 250°F. Cook fat side up until 195–203°F inside, about 1½ hours per pound.",480],["Stir the vinegar, water, pepper flakes, sugar and 1 teaspoon salt for a Carolina vinegar sauce.",0],["Wrap the pork loosely and rest it.",30],["Pull the meat into shreds, discarding fat and bone, and toss with some of the sauce.",0],["Serve on soft buns with coleslaw on top.",0]]},

{id:"gumbo",n:"Chicken and Sausage Gumbo",c:"Mains",p:"chicken",d:3,t:150,s:8,k:["roux","trinity"],sp:["cajun","thyme","bay","garlic","green-onion","file"],
tip:"Have the trinity chopped before you start the roux. Once the roux is dark you can't walk away.",
i:[[0.75,"cup","vegetable oil"],[0.75,"cup","all-purpose flour"],[1,"","large onion, diced"],[1,"","green bell pepper, diced"],[3,"","celery ribs, diced"],[4,"","garlic cloves, minced"],[1,"lb","andouille sausage, sliced"],[2,"lb","boneless chicken thighs, cut up"],[8,"cup","chicken stock"],[2,"","bay leaves"],[2,"tsp","Cajun seasoning"],[1,"tsp","dried thyme"],[3,"","green onions, sliced"],[4,"cup","cooked white rice"]],
st:[["Brown the sausage in a heavy pot and set it aside. Season and brown the chicken and set it aside.",10],["Add the oil, whisk in the flour and stir constantly on medium-low until the roux is the color of milk chocolate.",40],["Add the onion, bell pepper and celery. This stops the roux from browning. Cook until soft, then add the garlic.",6],["Slowly whisk in the stock. Add the bay leaves, Cajun seasoning, thyme and the meats.",0],["Simmer uncovered, skimming off fat now and then. Taste and season.",60],["Remove the bay leaves. Serve over rice with green onions, and a pinch of filé if you have it.",0]]},

{id:"red-beans-rice",n:"Red Beans and Rice",c:"Mains",p:"pork",d:2,t:180,s:8,w:"Soak beans overnight",k:["trinity"],sp:["cajun","thyme","bay","garlic"],
tip:"Mash some beans against the side of the pot near the end. That's what makes them creamy.",
i:[[1,"lb","dried red kidney beans, soaked overnight"],[1,"lb","andouille or smoked sausage, sliced"],[1,"","smoked ham hock"],[1,"","onion, diced"],[1,"","green bell pepper, diced"],[2,"","celery ribs, diced"],[4,"","garlic cloves, minced"],[8,"cup","water or stock"],[2,"","bay leaves"],[1,"tsp","dried thyme"],[1,"tsp","Cajun seasoning"],[4,"cup","cooked white rice"]],
st:[["Drain the soaked beans.",0],["Brown the sausage and set it aside. Cook the onion, pepper and celery in the fat, then add the garlic.",10],["Add the beans, ham hock, water, bay leaves, thyme and Cajun seasoning. Boil, then simmer partly covered until the beans are creamy.",150],["Mash about a cup of beans against the side of the pot to thicken.",0],["Add the sausage back, pull the meat off the ham hock and stir it in. Simmer.",20],["Season and serve over rice with hot sauce.",0]]},

{id:"jambalaya",n:"Jambalaya",c:"Mains",p:"seafood",d:2,t:75,s:6,k:["trinity"],sp:["cajun","garlic","green-onion"],
tip:"Once the lid goes on, leave it on. Lifting it lets the steam out and the rice cooks unevenly.",
i:[[2,"tbsp","vegetable oil"],[12,"oz","andouille sausage, sliced"],[1,"lb","chicken thighs, cubed"],[1,"","onion, diced"],[1,"","green bell pepper, diced"],[2,"","celery ribs, diced"],[3,"","garlic cloves, minced"],[1,"can","(14 oz) diced tomatoes"],[2,"cup","long-grain white rice"],[3.5,"cup","chicken stock"],[2,"tsp","Cajun seasoning"],[1,"lb","shrimp, peeled"],[3,"","green onions, sliced"]],
st:[["Brown the sausage, then the chicken, in the oil. Set the meat aside.",10],["Cook the onion, pepper and celery, then the garlic.",7],["Stir in the rice to coat it, then add the tomatoes, stock, Cajun seasoning and meats. Bring to a boil.",2],["Cover, turn the heat to low and cook without lifting the lid.",20],["Lay the shrimp on top, cover again and cook until pink and the rice is tender.",6],["Fluff and stir in the green onions.",0]]},

{id:"fried-catfish",n:"Fried Catfish",c:"Mains",p:"seafood",d:1,t:35,s:4,k:["dredge","fry"],sp:["cajun"],
tip:"Fine cornmeal gives a lighter, crispier crust than coarse.",
i:[[4,"","catfish fillets"],[1,"cup","buttermilk"],[1,"tsp","hot sauce"],[1,"cup","fine yellow cornmeal"],[0.25,"cup","all-purpose flour"],[2,"tsp","Cajun seasoning"],[1,"tsp","salt"],[4,"cup","oil for frying"],[1,"","lemon, cut in wedges"]],
st:[["Soak the fillets in buttermilk and hot sauce.",15],["Mix the cornmeal, flour, Cajun seasoning and salt.",0],["Heat the oil to 350°F.",10],["Dredge each fillet in the cornmeal mix and press it on.",0],["Fry two at a time until golden and the fish flakes.",5],["Drain on a rack, salt right away and serve with lemon.",0]]},

{id:"pot-roast",n:"Southern Pot Roast",c:"Mains",p:"beef",d:1,t:240,s:6,k:["braise"],sp:["thyme","black-pepper","garlic"],
tip:"Chuck roast is the right cut. Its fat and connective tissue melt into tender meat over long cooking.",
i:[[3.5,"lb","beef chuck roast"],[2,"tsp","salt"],[1,"tsp","black pepper"],[2,"tbsp","vegetable oil"],[1,"","onion, cut in wedges"],[3,"","garlic cloves"],[2,"tbsp","tomato paste"],[2,"cup","beef stock"],[1,"tbsp","Worcestershire sauce"],[2,"sprig","fresh thyme"],[1.5,"lb","small potatoes"],[4,"","carrots, cut in chunks"]],
st:[["Heat the oven to 300°F. Season the roast all over.",0],["Sear the roast in a Dutch oven on all sides and set it aside.",10],["Cook the onion, then the garlic and tomato paste for 1 minute.",4],["Add the stock, Worcestershire and thyme, scrape the pot, return the roast, cover and bake.",120],["Add the potatoes and carrots and bake until everything is fork-tender.",75],["Rest the roast before slicing.",10]]},

{id:"nashville-hot",n:"Nashville Hot Chicken",c:"Mains",p:"chicken",d:3,t:75,s:4,k:["dredge","fry"],sp:["cayenne","paprika","smoked-paprika","garlic-powder","black-pepper"],
tip:"Ladle the hot oil into the spice paste carefully. It sizzles and blooms the cayenne, and that's the whole point.",
i:[[2,"lb","chicken tenders or boneless thighs"],[1,"cup","buttermilk"],[1,"tbsp","hot sauce"],[2,"cup","all-purpose flour"],[2,"tsp","salt"],[1,"tsp","black pepper"],[4,"cup","oil for frying"],[2,"tbsp","cayenne pepper"],[1,"tbsp","brown sugar"],[1,"tsp","smoked paprika"],[0.5,"tsp","garlic powder"],[4,"slice","white bread"],[1,"cup","dill pickle chips"]],
st:[["Marinate the chicken in buttermilk and hot sauce.",60],["Dredge in flour seasoned with salt and pepper, then let it rest.",10],["Fry at 350°F until 165°F inside.",7],["Whisk the cayenne, brown sugar, smoked paprika and garlic powder in a heatproof bowl. Carefully ladle in ½ cup of the hot frying oil.",0],["Brush the spicy paste all over the hot chicken.",0],["Serve on white bread with pickles.",0]]},

{id:"smothered-chicken",n:"Smothered Chicken",c:"Mains",p:"chicken",d:2,t:75,s:4,k:["dredge","roux","braise"],sp:["poultry","black-pepper","garlic"],
tip:"Cook the flour in the drippings until it's the color of peanut butter for a deeper gravy.",
i:[[8,"","bone-in chicken thighs"],[2,"tsp","poultry seasoning"],[1,"tsp","salt"],[1,"tsp","black pepper"],[0.5,"cup","all-purpose flour"],[0.25,"cup","vegetable oil"],[1,"","onion, sliced"],[1,"","green bell pepper, sliced"],[3,"","garlic cloves, minced"],[2.5,"cup","chicken stock"]],
st:[["Season the chicken and dredge it in flour. Save 3 tablespoons of the flour.",0],["Brown the chicken, skin side down first, about 5 minutes a side. Set aside.",10],["Cook the onion and pepper until soft, then add the garlic.",6],["Sprinkle in the saved flour and stir into a light brown roux.",3],["Whisk in the stock, return the chicken, cover and simmer.",40],["Uncover to let the gravy thicken, then serve over rice.",5]]},

{id:"chicken-pot-pie",n:"Chicken Pot Pie",c:"Mains",p:"chicken",d:2,t:80,s:6,k:["roux"],sp:["thyme","black-pepper"],
tip:"Let the pie rest before cutting so the filling sets instead of running.",
i:[[6,"tbsp","butter"],[1,"","onion, diced"],[2,"","carrots, diced"],[2,"","celery ribs, diced"],[0.33,"cup","all-purpose flour"],[1.75,"cup","chicken stock"],[0.75,"cup","milk"],[3,"cup","cooked chicken, shredded"],[1,"cup","frozen peas"],[1,"tsp","dried thyme"],[1,"tsp","salt"],[2,"","9-inch pie crusts"],[1,"","egg, beaten (for wash)"]],
st:[["Heat the oven to 400°F.",0],["Melt the butter and cook the onion, carrots and celery.",6],["Stir in the flour for 2 minutes, then whisk in the stock and milk. Simmer until thick.",6],["Stir in the chicken, peas, thyme and salt.",0],["Line a pie dish with one crust, add the filling, top with the second crust, crimp, cut vents and brush with egg.",0],["Bake until deep golden.",38],["Rest before serving.",15]]},

{id:"etouffee",n:"Crawfish Étouffée",c:"Mains",p:"seafood",d:3,t:60,s:6,k:["roux","trinity"],sp:["cajun","garlic","green-onion"],
tip:"Étouffée uses a blond roux, lighter than gumbo's. Stop when it looks like peanut butter.",
i:[[0.5,"cup","butter"],[0.5,"cup","all-purpose flour"],[1,"","onion, diced"],[1,"","green bell pepper, diced"],[2,"","celery ribs, diced"],[3,"","garlic cloves, minced"],[2,"cup","seafood or chicken stock"],[1,"can","(14 oz) diced tomatoes"],[2,"tsp","Cajun seasoning"],[2,"lb","crawfish tails (or peeled shrimp)"],[3,"","green onions, sliced"],[4,"cup","cooked white rice"]],
st:[["Melt the butter, whisk in the flour and stir until it's the color of peanut butter.",12],["Add the onion, pepper and celery, then the garlic.",6],["Whisk in the stock a little at a time. Add the tomatoes and Cajun seasoning and simmer.",20],["Add the crawfish and simmer until heated through.",6],["Stir in the green onions, taste for salt, and serve over rice.",0]]},

{id:"oxtails",n:"Smothered Oxtails",c:"Mains",p:"beef",d:2,t:240,s:6,k:["braise"],sp:["allspice","thyme","black-pepper","garlic"],
tip:"Brown the oxtails in batches with space between them. Crowded meat steams instead of browning.",
i:[[3,"lb","oxtails"],[2,"tsp","salt"],[1,"tsp","black pepper"],[1,"tsp","ground allspice"],[2,"tbsp","vegetable oil"],[1,"","onion, chopped"],[4,"","garlic cloves, minced"],[2,"tbsp","tomato paste"],[4,"cup","beef stock"],[2,"tbsp","Worcestershire sauce"],[3,"sprig","fresh thyme"],[1,"can","(15 oz) butter beans, drained"],[1,"tbsp","cornstarch mixed with 2 tbsp water"]],
st:[["Season the oxtails with salt, pepper and allspice.",0],["Brown them in batches and set aside.",10],["Cook the onion, then the garlic and tomato paste.",5],["Return the meat, add stock, Worcestershire and thyme. Cover and simmer low until the meat falls off the bone.",180],["Add the butter beans and cornstarch slurry and simmer until the gravy thickens. Serve over rice.",10]]},

{id:"salmon-croquettes",n:"Salmon Croquettes",c:"Mains",p:"seafood",d:1,t:30,s:4,k:["fry","castiron"],sp:["old-bay","black-pepper"],
tip:"Chilling the patties before frying helps them hold together.",
i:[[2,"can","(14.75 oz) salmon, drained, skin and large bones removed"],[2,"","eggs"],[0.5,"cup","crushed saltine crackers"],[0.25,"cup","yellow cornmeal"],[0.5,"","onion, grated"],[1,"tsp","Old Bay seasoning"],[0.5,"tsp","black pepper"],[0.5,"cup","vegetable oil"]],
st:[["Flake the salmon into a bowl.",0],["Mix in the eggs, crackers, cornmeal, onion, Old Bay and pepper.",0],["Shape 8 patties and chill them.",10],["Heat the oil in a skillet over medium heat.",3],["Fry until golden, 3–4 minutes per side.",7],["Drain and serve with grits or tartar sauce.",0]]},

{id:"lowcountry-boil",n:"Lowcountry Boil",c:"Mains",p:"seafood",d:1,t:60,s:8,k:[],sp:["old-bay","bay"],
tip:"Add everything in order of how long it takes to cook, so the shrimp go in last.",
i:[[16,"cup","water"],[0.5,"cup","Old Bay seasoning"],[2,"","lemons, halved"],[1,"","onion, quartered"],[2,"lb","small red potatoes"],[1,"lb","smoked sausage, cut in 2-inch pieces"],[6,"","ears corn, halved"],[3,"lb","shell-on large shrimp"],[0.5,"cup","butter, melted"]],
st:[["Bring the water, Old Bay, lemons and onion to a boil in a big pot.",10],["Add the potatoes and boil.",10],["Add the sausage and corn and boil.",8],["Add the shrimp and cook until pink, then turn off the heat.",3],["Drain, pour it all onto a paper-lined table, drizzle with butter and sprinkle on more Old Bay.",0]]},

{id:"shrimp-po-boy",n:"Shrimp Po' Boy",c:"Mains",p:"seafood",d:2,t:40,s:4,k:["dredge","fry"],sp:["cajun"],
tip:"Use light, crackly French bread. A dense roll fights the shrimp.",
i:[[1,"lb","medium shrimp, peeled"],[1,"cup","buttermilk"],[1,"cup","yellow cornmeal"],[0.5,"cup","all-purpose flour"],[2,"tsp","Cajun seasoning"],[4,"cup","oil for frying"],[4,"","French bread rolls"],[0.5,"cup","mayonnaise"],[1,"tbsp","Creole mustard"],[1,"tsp","hot sauce"],[2,"cup","shredded lettuce"],[2,"","tomatoes, sliced"],[0.5,"cup","dill pickle chips"]],
st:[["Soak the shrimp in buttermilk.",10],["Mix the cornmeal, flour and Cajun seasoning.",0],["Heat the oil to 350°F.",10],["Dredge the shrimp and fry in batches until golden.",2],["Stir the mayo, mustard and hot sauce into a quick sauce.",0],["Split and toast the rolls, spread the sauce and pile on lettuce, tomato, pickles and shrimp.",0]]},
